name: crm-service

services:
  crm-service:
    build:
      context: .
#    image: marcosav/tam-crm-service:latest
    depends_on:
      - postgres
      - localstack
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: crm
      DB_USERNAME: db-user
      DB_PASSWORD: db-password
      AWS_REGION: eu-west-1
      AWS_BUCKET: crm-bucket
      AWS_ACCESS_KEY: secret
      AWS_SECRET_KEY: secret
      AWS_ACCESS_KEY_ID: secret
      AWS_SECRET_ACCESS_KEY: secret
      AWS_ENDPOINT: http://localstack:4566
      AWS_EXTERNAL_ENDPOINT: http://localhost:4566
      JWT_SECRET: thisisjustfordevelopmentpurposessodefineyourownsecretwiththisenv

  postgres:
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-password
      POSTGRES_DB: crm
    volumes:
      - postgres:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.29
    depends_on:
      - postgres
    environment:
      DB_NAME: crm
      DB_USERNAME: db-user
      DB_PASSWORD: db-password
    volumes:
      - ./db/config/:/liquibase/changelog
      - ./crm-service/:/liquibase/changelog/crm-service
      - ./init_data.sql:/init_data.sql
    entrypoint: /bin/sh -c
    command: >
      "
        liquibase --searchPath=/liquibase/changelog --changeLogFile=changelog.xml --url=jdbc:postgresql://postgres:5432/$${DB_NAME} --username=$${DB_USERNAME} --password=$${DB_PASSWORD} update
        liquibase --sql-file=/init_data.sql --url=jdbc:postgresql://postgres:5432/$${DB_NAME} --username=$${DB_USERNAME} --password=$${DB_PASSWORD} execute-sql
      "

  localstack:
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      SERVICES: s3:4566
      DEBUG: 1
      DOCKER_SOCK: var/run/docker.sock
      PERSISTENCE: 1
      LS_LOG: trace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.localstack:/var/lib/localstack

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      AWS_ACCESS_KEY_ID: secret
      AWS_SECRET_ACCESS_KEY: secret
      AWS_DEFAULT_REGION: eu-west-1
      AWS_BUCKET: crm-bucket
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3 mb s3://$${AWS_BUCKET} --region=$${AWS_DEFAULT_REGION}
      "

volumes:
  postgres: