aws:
  region: ${AWS_REGION:eu-west-1}
  s3:
    bucket: ${AWS_BUCKET:crm-bucket}
    access-key: ${AWS_ACCESS_KEY:secret}
    secret-key: ${AWS_SECRET_KEY:secret}
    endpoint: ${AWS_ENDPOINT:https://localhost.localstack.cloud:4566}

logging:
  level:
    com.gmail.marcosav2010.crm: ${LOG_LEVEL:DEBUG}