name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'develop'

  pull_request:
    types: [ opened, reopened ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - name: Execute Unit & Integration Tests with Coverage
        run: mvn verify -P integration-tests

      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/report-aggregate/target/site/jacoco-aggregate/jacoco.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50

      - name: Check coverage
        if: ${{ steps.jacoco.outputs.coverage-overall < 50.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is under 50% (' + '${{ steps.jacoco.outputs.coverage-overall }}' + '%)')
